Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charizard
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Gengar
	dba Cry_IvysaurOld
	dba Cry_Nidoking
	dba Cry_Nidoqueen
	dba Cry_Exeggcute
	dba Cry_Lickitung
	dba Cry_Exeggcutor
	dba Cry_Pip
	dba Cry_Gyaoon
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Tengela
	dba Cry_Blastoise
	dba Cry_Pinsir
	dba Cry_Arcanine
	dba Cry_Scyther
	dba Cry_Gyarados
	dba Cry_Shellder
	dba Cry_Cubone
	dba Cry_Tentacool
	dba Cry_Lapras
	dba Cry_Gastly
	dba Cry_Karabatheo
	dba Cry_Starmie
	dba Cry_Slowbro
	dba Cry_34
	dba Cry_36
	dba Cry_Rattata
	dba Cry_Kingsauras
	dba Cry_Graveler
	dba Cry_Ponyta
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Donphan
	dba Cry_Earthtron
