; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_Title
	dba Music_Route1
	dba Music_Route3
	dba Music_Route11
	dba Music_PokeChannel
	dba Music_KantoLeader
	dba Music_KantoTrainer
	dba Music_KantoWild
	dba Music_PokeCenter
	dba Music_Maniac
	dba Music_Girl
	dba Music_Youth
	dba Music_Heal
	dba Music_Lavender
	dba Music_DiglettCave
	dba Music_MtMoon
	dba Music_Tour
	dba Music_GameCorner
	dba Music_Bike
	dba Music_HallOfFame
	dba Music_Viridian
	dba Music_Celadon
	dba Music_TrainerWin
	dba Music_WildWin
	dba Music_LeaderWin
	dba Music_Square
	dba Music_Gym
	dba Music_Pallet
	dba Music_OaksLab
	dba Music_Oak
	dba Music_Rival
	dba Music_RivalAfter
	dba Music_Surf
	dba Music_Event
	dba Music_ChampCutscene
	dba Music_Credits
	dba Music_Azalea
	dba Music_Cherrygrove
	dba Music_E4Rival
	dba Music_JohtoCave
	dba Music_JohtoWild
	dba Music_JohtoTrainer
	dba Music_Route30
	dba Music_Ecruteak
	dba Music_Violet
	dba Music_JohtoLeader
	dba Music_Champ
	dba Music_Cerulean
	dba Music_Route24
	dba Music_Elm
	dba Music_E4RivalAfter
	dba Music_Route29
	dba Music_Route36
	dba Music_SSAnne
	dba Music_Trade1
	dba Music_Trade2
	dba Music_CinnabarGen1
	dba Music_LavenderGen1
	dba Music_Mansion
	dba Music_SilentHills
	dba Music_Goldenrod
	dba Music_Vermilion
	dba Music_PokeChannel
	dba Music_PokeFlute
	dba Music_TinTower
	dba Music_SproutTower
	dba Music_BurnedTower
	dba Music_Lighthouse
	dba Music_LakeOfRage
	dba Music_League
	dba Music_Route37
	dba Music_RocketHQ
	dba Music_DragonsDen
	dba Music_NightWild
	dba Music_UnownSignal
	dba Music_Capture
	dba Music_Route26
	dba Music_Mom
	dba Music_PokeTower
	dba Music_Lullaby
	dba Music_SurfGen1
	dba Music_CutsceneLight
	dba Music_IntroFight
	dba Music_Jigglypuff
	dba Music_AlphInterior
	dba Music_SilphCo
	dba Music_CType
	dba Music_Hall
	dba Music_BikeGen1
	dba Music_RocketSignal
	dba Music_Printer
	dba Music_Cinnabar
